# Generated by Django 4.1.3 on 2022-11-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('purchased', 'Puchased'), ('wishlist', 'Wishlist'), ('not_purchased', 'Not Purchased')], default='not_purchased', max_length=13),
        ),
    ]
